### ISSUE TITLE
timeline sample.eac3/core universe does not work in Media encoder

### ISSUE THREAD

**Issue by ValZapod** [VoidXH/Cavern#74]
On fcd27df320629ac67371e13eae45687f911cadbb, this patch fixes them, but not dolby-test-tones_7_1_4.mp4.

```
diff --git a/Cavern.Format/Output/Environment/BroadcastWaveFormatWriter.cs b/Cavern.Format/Output/Environment/BroadcastWaveFormatWriter.cs
index c57cd5d..61af300 100644
--- a/Cavern.Format/Output/Environment/BroadcastWaveFormatWriter.cs
+++ b/Cavern.Format/Output/Environment/BroadcastWaveFormatWriter.cs
@@ -26,11 +26,6 @@ namespace Cavern.Format.Environment {
         /// </summary>
         public double FinalFeedbackStart;

-        /// <summary>
-        /// If an object is moving linearly for this long, the positions will be merged.
-        /// </summary>
-        public double MaxObjectMergeTime = 120;
-
         /// <summary>
         /// The main PCM exporter.
         /// </summary>
@@ -92,7 +87,6 @@ namespace Cavern.Format.Environment {
             Vector3 scaling = new Vector3(1) / Listener.EnvironmentSize;
             double timeScaling = 1.0 / Source.SampleRate;
             ADMTimeSpan updateTime = new ADMTimeSpan(Source.UpdateRate * timeScaling),
-                maxCombinationSpan = new ADMTimeSpan(MaxObjectMergeTime),
                 newOffset = new ADMTimeSpan(samplesWritten * timeScaling);

             int sourceIndex = 0;
@@ -102,7 +96,7 @@ namespace Cavern.Format.Environment {
                 Vector3 scaledPosition = Vector3.Clamp(source.Position * scaling, minusOne, Vector3.One);
                 if (size == 0 || movement[size - 1].Position != scaledPosition) {
                     bool replace = false;
-                    if (size > 1 && movement[size - 1].Duration < maxCombinationSpan) {
+                    if (size > 1) {
                         float t = (float)QMath.LerpInverse(movement[size - 2].Offset.TotalSeconds, newOffset.TotalSeconds,
                             movement[size - 1].Offset.TotalSeconds);
                         Vector3 inBetween = QMath.Lerp(movement[size - 2].Position, scaledPosition, t),
diff --git a/Cavern.Format/Output/Environment/DolbyAtmosBWFWriter.cs b/Cavern.Format/Output/Environment/DolbyAtmosBWFWriter.cs
index e33ae1b..33bf1f9 100644
--- a/Cavern.Format/Output/Environment/DolbyAtmosBWFWriter.cs
+++ b/Cavern.Format/Output/Environment/DolbyAtmosBWFWriter.cs
@@ -23,9 +23,7 @@ namespace Cavern.Format.Environment {
         /// <param name="staticObjects">Objects that should be exported as a bed channel if possible</param>
         public DolbyAtmosBWFWriter(BinaryWriter writer, Listener source, long length, BitDepth bits,
             (ReferenceChannel, Source)[] staticObjects) :
-            base(writer, ExtendWithMuteTarget(source, staticObjects), length, bits) {
-            MaxObjectMergeTime = 16.0 / source.SampleRate;
-        }
+            base(writer, ExtendWithMuteTarget(source, staticObjects), length, bits){ }

         /// <summary>
         /// ADM BWF exporter with Dolby Atmos compatibility options.
diff --git a/Cavern.Format/Transcoders/AudioDefinitionModelElements/ADMTimeSpan.cs b/Cavern.Format/Transcoders/AudioDefinitionModelElements/ADMTimeSpan.cs
index b5c2c27..2d45744 100644
--- a/Cavern.Format/Transcoders/AudioDefinitionModelElements/ADMTimeSpan.cs
+++ b/Cavern.Format/Transcoders/AudioDefinitionModelElements/ADMTimeSpan.cs
@@ -28,7 +28,7 @@
         /// </summary>
         public ADMTimeSpan(double seconds) {
             this.seconds = (int)seconds;
-            fraction = (int)(seconds % 1 * 100000 + 0.5);
+            fraction = (int)(seconds % 1 * 100000);
         }

         /// <summary>
@@ -102,7 +102,7 @@
         /// <summary>
         /// Display the timestamp as a floating-point number with a dot.
         /// </summary>
-        public string ToInvariantFloatString() => $"{seconds}.{fraction:00000}";
+        public string ToInvariantFloatString() => $"{seconds}.{fraction}";

         /// <summary>
         /// Checks if this time span is equal to another object.
```

**Comment by VoidXH** [comment]
Diffs should be added with a pull request. This is not a fix, this removes a feature because it fixes some content, and only on your side. This is a timing feature which should not affect a working encoder. Proper root cause analysis is needed for any change regarding ADM.

**Comment by ValZapod** [comment]
That feature should be an option then.

I will submit a pull when I fix dolby-test-tones_7_1_4.mp4

**Comment by VoidXH** [comment]
> That feature should be an option then.

It is optional and only used for Atmos BWF files. The compact options does not have it. Setting `MaxObjectMergeTime` to any large value will disable this.

> I will submit a pull when I fix dolby-test-tones_7_1_4.mp4

Please don't just try removing features. That will not help, even if one or two content works, there is absolutely no guarantee that it works for everything else. The only proper fix is the one that's based on the Dolby plugin's check. Unless we know what it checks, we can't fix it, and all features should stay.

**Comment by ValZapod** [comment]
>The compact options does not have it.

It also just prints `ERROR: Content was not authored with Dolby tools.` so useless for production. What is the app that is supposed to use that?

>there is absolutely no guarantee that it works for everything else

It worked for everything until recently including dolby-test-tones_7_1_4.mp4.

BTW, here are two files for timeline sample.eac3, one works (with this patch on top of static), one does not in Media Encoder. May be interesting for you.


[twofiles.zip](https://github.com/VoidXH/Cavern/files/10528149/twofiles.zip)

**Comment by ValZapod** [comment]
>we can't fix it

Do you want to fix core universe??? Cause that fixed it, do you want XML?

**Comment by ValZapod** [comment]
OMG, dolby-test-tones_7_1_4.mp4's ADM was broken even before 5a2fe5d78f85ed657099bb75be30e4102f45fb56 which fixed render for that file. So...

It was forver broken.

**Comment by VoidXH** [comment]
> Do you want to fix core universe???

Whatever is fixed by randomli toggling features, does not fix everything. Movies just don't work, with or without any commit.

**Comment by ValZapod** [comment]
This whole mistake that Dolby media Encoder produces looks like the same mistake that happens if you give it ADM without AXML produces by separate XML + ADM. Interesting, maybe it cannot see XML.

Maybe that is indeed 

> The last bytes are part of the object metadata block. While it's structure is unknown and written as zeros by Cavern, its small size rules out watermarking.

**Comment by VoidXH** [comment]
Maybe some weird byte alignment, yes. Is the axml/dbmd marker at some weird position in files that don't work? There are some masters (Netflix open library) that have zero padding between the two that isn't part of any RIFF blocks.

**Comment by VoidXH** [comment]
Indeed, Dolby files are aligned at DWORDs. This is also not part of any standard, but worth a shot.

**Comment by VoidXH** [comment]
I can't believe it worked... Please try e4227691475fe95685ad05208013e352cbe02bb0.

**Comment by VoidXH** [comment]
You can even cut back on the number of beds, huge optimizations are coming to file sizes.

**Comment by ValZapod** [comment]
dolby-test-tones_7_1_4.mp4's ADM works now. Very good, it must work for everything now. Davinci issue is closed, we still need to verify/fix XML issue.

**Comment by ValZapod** [comment]
>Davinci issue is closed

It is not closed. It does not like smaller track files.

**Comment by VoidXH** [comment]
Fix in an hour.

**Comment by VoidXH** [comment]
Done in f5ed676f99e4dab6b56ebece2d6951ab75bd7e48 and released.

**Comment by ValZapod** [comment]
Thanks

**Comment by VoidXH** [comment]
Sorry, wrong call, one thing is missing.

**Comment by VoidXH** [comment]
Now it's fixed in latest commit/release.

**Comment by ValZapod** [comment]
Still does not work after https://github.com/VoidXH/Cavern/commit/f5ed676f99e4dab6b56ebece2d6951ab75bd7e48

**Comment by ValZapod** [comment]
> Now it's fixed in latest commit/release.

Where is latest commit?

**Comment by VoidXH** [comment]
In 051d746569e5d9d74c8f82b0d9b3d3acb551595c or on the website.

**Comment by ValZapod** [comment]
Works now indeed. Thanks.
