### ISSUE TITLE
Issues with 9.1.6

### ISSUE THREAD

**Issue by junh1024** [VoidXH/Cavern#83]
### Intro

Hi. Thank you for adding Dolby Atmos support to Cavern. Some issues:

### 1. Layout inconsistency with 9.1.6 btw Cavern & Cavern lite ? :

Cavern uses a 916 Dolby layout with Top side & back, but Cavern lite uses/mentions Top center& Top back center. Cavern lite should use the same layout as Cavern. 716 & 516 should also use Top side speakers in Cavern lite.

### 2. Channel order

The channel order for 916 should be L,R,C,LFE,Lss,Rss(side),Lrs,Rrs(back),Lw,Rw,Ltf,Rtf,TpSiL,TpSiR,Ltb,Rtb according to the Dolby document "[Additional Audio Channels and Soundfields for Immersive Audio](https://developer.dolby.com/globalassets/technology/atmos/additional-channels-for-immersive-audio.pdf)" . Note that This is SMPTE-Dolby order, not SMPTE-Microsoft. All Dolby/Atmos 916 files have this order. Other  layouts should also follow this order.

### 3. Rendering

[GVR-151-lab-90d-916.zip](https://github.com/VoidXH/Cavern/files/10722369/GVR-151-lab-90d-916.zip)

I have attached a channel test for 7.1.6 . When rendered to 916, 1 channel should render to 1 speaker only.  But there's bleed to multiple others, which is wrong. This happens to 7.1.6 and 5.1.6 too. Please fix. Maybe related to Issue 1 ?

**Comment by VoidXH** [comment]
Done in 172a452a957c1d918ba0bf4e800301f6e385908a, release in a few hours after other issues are done.

**Comment by junh1024** [comment]
Some issues:

### 1. The channel order is still incorrect in the decoded file of 9.1.6

You have:  L,R,C,LFE,Lss,Rss,Lw,Rw, (wide), Lrs,Rrs (back), Ltf,Rtf,TpSiL,TpSiR,Ltb,Rtb
The specification is: L,R,C,LFE,Lss,Rss,Lrs,Rrs (back),Lw,Rw, (wide) Ltf,Rtf,TpSiL,TpSiR,Ltb,Rtb

516 & 716 look ok. 

### 2. 7.1.4 order
Would you like to change the existing 7.1.4 name to 7.1.4 SMPTE-Microsoft, and add a new one called 7.1.4 SMPTE-Dolby which [reverses](https://github.com/VoidXH/Cavern/issues/56#issuecomment-1375105450) the back & sides as per issue #56 ?

### 3. Naming in GUI

I would suggest you name the variants 9.1.6 Dolby & 9.1.6 Microsoft which refers to layout, rather than SMPTE & WAVE.

9.1.6 is a Dolby-ism (no other company has this layout).

SMPTE just refers to the channel order, SMPTE has nothing to say about the layout AFAIK. SMPTE especially has nothing to say about 9.1.6, only 5.1. Hence the SMPTE-Dolby & SMPTE-Microsoft etc in my initial post to hint that Dolby & Microsoft extended the SMPTE 5.1 order in different ways, and to differentiate it from the Film order. 

### 4. Display wiring
Please update display wiring to reflect the order in #1, as currently, Display wiring shows 4 top side wirings for 516,716,916, which is nonsensical.

### 5. render WAV should be allowed for all layouts
Currently it's disallowed for some layouts. Should I continue here, or file an issue?

Thanks for updating Cavern.

**Comment by VoidXH** [comment]
The L R C LFE RL RR SL SR channel order (calling the surrounds rears originally) is an SMPTE standard from 1990. Microsoft (and IBM) created RIFF WAVE in 1991 according to this standard. Anything that follows it is called standard, and there is Dolby with late Atmos. The only X.X.6 layout DD+ supports fully PCM-coded is actually the standard, that's why those layouts are needed (for easy encoding). Dolby added rears after surrounds because in cinema, the PCM channels are directly wired into the amplifiers. For 7.1 systems, having to choose between using sides and rears for 5.1, it's better to keep the sides, and make rears optional. The actual 7.1 standard evolved differently, adding sides, having called the surrounds rears before, suggesting a rear corner placement (everyone followed this, except Dolby). That said:
* The incorrect wide channel insertions were fixed.
* There is now a "Swap side/rear channels" option under "Rendering" to swap sides and rears for any export.
* By default, it's always *correctly* RL RR SL SR, which can be swapped by the option to use the export with non-conformant software.
* The layouts were renamed to "with top sides" and "for WAVE" to avoid confusion.
* The wiring popup now just displays the channels of the file above 8 channels, because there's no interface there which changes the channel order when this many are used.

Done in 90a2d954887ddd6b3e669da4abdc032a04988b31, released.

**Comment by junh1024** [comment]
Thanks for the latest update. Wiring GUI looks better, order seems right for 9.1.6

#### 5. render WAV should be allowed for all layouts

Maybe you can make a  Rendering menu option "allow WAV with arbitrary layout" or just allow it regardless? Currently: input > temp wav > mkv > demuxed wav is very inefficient, I need wav anyway since most of my editing apps don't support mkv.

**Comment by VoidXH** [comment]
Done in 2a236e713e721ab6d48670e3964377b071eaf815 and released.

**Comment by VoidXH** [comment]
Sorry, that was the result of a minor API change. It's fixed in 20be21c9e81f999cc8258d611702a283e784789b and the latest release. It'll be introduced in the driver too with #76.

**Comment by ValZapod** [comment]
>L R C LFE RL RR SL SR channel order (calling the surrounds rears originally) is an SMPTE standard from 1990

Here is Dolby saying SMPTE is to be used: https://youtu.be/qeaGWdSXvV4?t=1372
