### ISSUE TITLE
Some artifacts in the start

### ISSUE THREAD

**Issue by ValZapod** [VoidXH/Cavern#9]
Sample
https://disk.yandex.ru/d/J0AfEKjMvZtf2A

It causes artifacts in the start (in Unity app) that also makes ADM not bitperfect if you do ADM and then again same ADM (looks like some uninitiliased stuff looking into Beyond compare). md5 of ADMs also not the same in sound ffmpeg -i fefe.wav  -c:a pcm_s24le -f md5 - so problem in not how XML is positioned. There are quite a lot of artificats when playing some music too.

**Comment by VoidXH** [comment]
There is a known bug of converting the same file twice in a row from the same window yields different results, but re-launching Cavernize GUI makes consistent results. However, importing the ADM and exporting it again is creating a different AXML (PCM stays the same). Looking into both.

**Comment by VoidXH** [comment]
Fixed in 658081826057d0b07e009eceaee13776fe562aa7.

**Comment by ValZapod** [comment]
This one is fixed, cool!

**Comment by ValZapod** [comment]
BTW, this file has a bug in Cavern driver, Headphones break on it (build Unity DLL with unity two dll changed from Unity Hub/Editor, what should you do next? Open 3D project in Unity alpha 2023, or 2D? How to load that dll? Or is cavern driver not fully open source?).

**Comment by VoidXH** [comment]
Yes, the frontend is closed source. How exactly do headphones break?

**Comment by ValZapod** [comment]
Heaphones renderer just produces some very low level noise.

**Comment by VoidXH** [comment]
I'll look into the headphone issue. The Unity DLL adds Cavern versions of Unity's audio components (e.g. AudioListener as AudioListener3D).

**Comment by VoidXH** [comment]
There is no reproducible headphone renderer issue, please attach a screen capture with audio about the issue and how it happens.

**Comment by ValZapod** [comment]
Then it just means you tested with HEAD of your private repo version? I tested obviously with the version on the website.

**Comment by VoidXH** [comment]
I tested with the current release.

**Comment by ValZapod** [comment]
> Reproduced in Driver HEAD.

But I do not have current HEAD? :)

**Comment by VoidXH** [comment]
Maybe my browser downloaded a cached file, this is a regular issue in Chrome.

**Comment by VoidXH** [comment]
Root cause found, FFT caching is not thread-safe. Might take a longer time.

**Comment by VoidXH** [comment]
Nvm, fixed in 7be589284ba80ae12bfa2f19afdacfcc3b4a0b7a. Will be included in the next release.

**Comment by ValZapod** [comment]
> Will be included in the next release.

Yep, headphones fixed. Nice. But artefacts in the very start still happen.

**Comment by ValZapod** [comment]
Nope, said too fast. It still breaks if you start with headphones on. 😉

**Comment by ValZapod** [comment]
why does this gets Channel(s): 26 channels in latest version? Also why cannotI use ffmpeg 0.wav method anymore?

**Comment by VoidXH** [comment]
> why does this get Channel(s): 26 channels in latest version?

Those are the 10 fake channels for Atmos bed hacking, only found in ADM BWF (Dolby Atmos).

> Also why cannot I use ffmpeg 0.wav method anymore?

Because FFmpeg is not used for decoding anymore.

**Comment by ValZapod** [comment]
>Those are the 10 fake channels for Atmos bed hacking, only found in ADM BWF (Dolby Atmos).

Yes, saw it after I posted. Bad design from Dolby. 

>10 bed channels always have to be present, even if they are empty.

**Comment by VoidXH** [comment]
No artifacts are reproducible when launching the latest driver with headphones on. What steps cause this issue?

**Comment by ValZapod** [comment]
You need to select headphones on, exit the app and then when you are reopen it (it will have saved position "on") there will be artefacts.

Simples fix is to turn off savibg that setting.

**Comment by VoidXH** [comment]
Is your version the latest, from 18th October?

**Comment by ValZapod** [comment]
Oh, yes. It is fixed now, some artefacts due to not real time only.
